DROP INDEX IF EXISTS idx_tracks_isrc;
DROP INDEX IF EXISTS idx_jobs_status;
DROP INDEX IF EXISTS idx_jobs_album;
DROP INDEX IF EXISTS idx_track_links_provider;
DROP INDEX IF EXISTS idx_track_links_track;
DROP INDEX IF EXISTS idx_album_links_provider;
DROP INDEX IF EXISTS idx_album_links_album;
DROP INDEX IF EXISTS idx_artist_links_provider;
DROP INDEX IF EXISTS idx_artist_links_artist;
DROP INDEX IF EXISTS idx_tracks_album;
DROP INDEX IF EXISTS idx_albums_artist;

DROP TABLE IF EXISTS download_jobs;
DROP TABLE IF EXISTS track_provider_links;
DROP TABLE IF EXISTS album_provider_links;
DROP TABLE IF EXISTS artist_provider_links;
DROP TABLE IF EXISTS tracks;
DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS artists;
