---
services:
  yoink:
    # version tags are available like 0.1.0 use main for bleeding edge (not recommended, you'll bleed)
    # the 0 and 0.x tags are not recommended as they may have breaking changes without a major version bump
    build: .
    container_name: yoink
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - yoink-data:/data
      - ./music:/music
      - ./development/slskd-data:/app
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./development/slskd-data:/app
      - ./music:/music
    env_file:
      - .env.docker
    restart: always

volumes:
  yoink-data:
