/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupPasswordRouteImport } from './routes/setup/password'
import { Route as AppWantedRouteImport } from './routes/_app/wanted'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppDownloadsRouteImport } from './routes/_app/downloads'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppLibraryRouteRouteImport } from './routes/_app/library/route'
import { Route as AppImportRouteRouteImport } from './routes/_app/import/route'
import { Route as AppArtistsRouteRouteImport } from './routes/_app/artists/route'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppLibraryIndexRouteImport } from './routes/_app/library/index'
import { Route as AppImportIndexRouteImport } from './routes/_app/import/index'
import { Route as AppArtistsIndexRouteImport } from './routes/_app/artists/index'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings/security'
import { Route as AppLibraryTracksRouteImport } from './routes/_app/library/tracks'
import { Route as AppLibraryArtistsRouteImport } from './routes/_app/library/artists'
import { Route as AppLibraryAlbumsRouteImport } from './routes/_app/library/albums'
import { Route as AppArtistsArtistIdRouteImport } from './routes/_app/artists/$artistId'
import { Route as AppArtistsArtistIdIndexRouteImport } from './routes/_app/artists/$artistId/index'
import { Route as AppArtistsArtistIdMergeAlbumsRouteImport } from './routes/_app/artists/$artistId/merge-albums'
import { Route as AppArtistsArtistIdAlbumsRouteImport } from './routes/_app/artists/$artistId/albums'
import { Route as AppArtistsArtistIdAlbumsIndexRouteImport } from './routes/_app/artists/$artistId/albums/index'
import { Route as AppArtistsArtistIdAlbumsAlbumIdRouteImport } from './routes/_app/artists/$artistId/albums/$albumId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup/password',
  path: '/setup/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWantedRoute = AppWantedRouteImport.update({
  id: '/wanted',
  path: '/wanted',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRouteRoute = AppLibraryRouteRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRouteRoute = AppImportRouteRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppArtistsRouteRoute = AppArtistsRouteRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLibraryRouteRoute,
} as any)
const AppImportIndexRoute = AppImportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppImportRouteRoute,
} as any)
const AppArtistsIndexRoute = AppArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppArtistsRouteRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppLibraryTracksRoute = AppLibraryTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AppLibraryRouteRoute,
} as any)
const AppLibraryArtistsRoute = AppLibraryArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AppLibraryRouteRoute,
} as any)
const AppLibraryAlbumsRoute = AppLibraryAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => AppLibraryRouteRoute,
} as any)
const AppArtistsArtistIdRoute = AppArtistsArtistIdRouteImport.update({
  id: '/$artistId',
  path: '/$artistId',
  getParentRoute: () => AppArtistsRouteRoute,
} as any)
const AppArtistsArtistIdIndexRoute = AppArtistsArtistIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppArtistsArtistIdRoute,
} as any)
const AppArtistsArtistIdMergeAlbumsRoute =
  AppArtistsArtistIdMergeAlbumsRouteImport.update({
    id: '/merge-albums',
    path: '/merge-albums',
    getParentRoute: () => AppArtistsArtistIdRoute,
  } as any)
const AppArtistsArtistIdAlbumsRoute =
  AppArtistsArtistIdAlbumsRouteImport.update({
    id: '/albums',
    path: '/albums',
    getParentRoute: () => AppArtistsArtistIdRoute,
  } as any)
const AppArtistsArtistIdAlbumsIndexRoute =
  AppArtistsArtistIdAlbumsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppArtistsArtistIdAlbumsRoute,
  } as any)
const AppArtistsArtistIdAlbumsAlbumIdRoute =
  AppArtistsArtistIdAlbumsAlbumIdRouteImport.update({
    id: '/$albumId',
    path: '/$albumId',
    getParentRoute: () => AppArtistsArtistIdAlbumsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/artists': typeof AppArtistsRouteRouteWithChildren
  '/import': typeof AppImportRouteRouteWithChildren
  '/library': typeof AppLibraryRouteRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/downloads': typeof AppDownloadsRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/wanted': typeof AppWantedRoute
  '/setup/password': typeof SetupPasswordRoute
  '/artists/$artistId': typeof AppArtistsArtistIdRouteWithChildren
  '/library/albums': typeof AppLibraryAlbumsRoute
  '/library/artists': typeof AppLibraryArtistsRoute
  '/library/tracks': typeof AppLibraryTracksRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/artists/': typeof AppArtistsIndexRoute
  '/import/': typeof AppImportIndexRoute
  '/library/': typeof AppLibraryIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/artists/$artistId/albums': typeof AppArtistsArtistIdAlbumsRouteWithChildren
  '/artists/$artistId/merge-albums': typeof AppArtistsArtistIdMergeAlbumsRoute
  '/artists/$artistId/': typeof AppArtistsArtistIdIndexRoute
  '/artists/$artistId/albums/$albumId': typeof AppArtistsArtistIdAlbumsAlbumIdRoute
  '/artists/$artistId/albums/': typeof AppArtistsArtistIdAlbumsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/downloads': typeof AppDownloadsRoute
  '/search': typeof AppSearchRoute
  '/wanted': typeof AppWantedRoute
  '/setup/password': typeof SetupPasswordRoute
  '/library/albums': typeof AppLibraryAlbumsRoute
  '/library/artists': typeof AppLibraryArtistsRoute
  '/library/tracks': typeof AppLibraryTracksRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/artists': typeof AppArtistsIndexRoute
  '/import': typeof AppImportIndexRoute
  '/library': typeof AppLibraryIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/artists/$artistId/merge-albums': typeof AppArtistsArtistIdMergeAlbumsRoute
  '/artists/$artistId': typeof AppArtistsArtistIdIndexRoute
  '/artists/$artistId/albums/$albumId': typeof AppArtistsArtistIdAlbumsAlbumIdRoute
  '/artists/$artistId/albums': typeof AppArtistsArtistIdAlbumsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/artists': typeof AppArtistsRouteRouteWithChildren
  '/_app/import': typeof AppImportRouteRouteWithChildren
  '/_app/library': typeof AppLibraryRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/downloads': typeof AppDownloadsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/wanted': typeof AppWantedRoute
  '/setup/password': typeof SetupPasswordRoute
  '/_app/artists/$artistId': typeof AppArtistsArtistIdRouteWithChildren
  '/_app/library/albums': typeof AppLibraryAlbumsRoute
  '/_app/library/artists': typeof AppLibraryArtistsRoute
  '/_app/library/tracks': typeof AppLibraryTracksRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/artists/': typeof AppArtistsIndexRoute
  '/_app/import/': typeof AppImportIndexRoute
  '/_app/library/': typeof AppLibraryIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/artists/$artistId/albums': typeof AppArtistsArtistIdAlbumsRouteWithChildren
  '/_app/artists/$artistId/merge-albums': typeof AppArtistsArtistIdMergeAlbumsRoute
  '/_app/artists/$artistId/': typeof AppArtistsArtistIdIndexRoute
  '/_app/artists/$artistId/albums/$albumId': typeof AppArtistsArtistIdAlbumsAlbumIdRoute
  '/_app/artists/$artistId/albums/': typeof AppArtistsArtistIdAlbumsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/artists'
    | '/import'
    | '/library'
    | '/dashboard'
    | '/downloads'
    | '/search'
    | '/settings'
    | '/wanted'
    | '/setup/password'
    | '/artists/$artistId'
    | '/library/albums'
    | '/library/artists'
    | '/library/tracks'
    | '/settings/security'
    | '/artists/'
    | '/import/'
    | '/library/'
    | '/settings/'
    | '/artists/$artistId/albums'
    | '/artists/$artistId/merge-albums'
    | '/artists/$artistId/'
    | '/artists/$artistId/albums/$albumId'
    | '/artists/$artistId/albums/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/downloads'
    | '/search'
    | '/wanted'
    | '/setup/password'
    | '/library/albums'
    | '/library/artists'
    | '/library/tracks'
    | '/settings/security'
    | '/artists'
    | '/import'
    | '/library'
    | '/settings'
    | '/artists/$artistId/merge-albums'
    | '/artists/$artistId'
    | '/artists/$artistId/albums/$albumId'
    | '/artists/$artistId/albums'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/artists'
    | '/_app/import'
    | '/_app/library'
    | '/_app/dashboard'
    | '/_app/downloads'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/wanted'
    | '/setup/password'
    | '/_app/artists/$artistId'
    | '/_app/library/albums'
    | '/_app/library/artists'
    | '/_app/library/tracks'
    | '/_app/settings/security'
    | '/_app/artists/'
    | '/_app/import/'
    | '/_app/library/'
    | '/_app/settings/'
    | '/_app/artists/$artistId/albums'
    | '/_app/artists/$artistId/merge-albums'
    | '/_app/artists/$artistId/'
    | '/_app/artists/$artistId/albums/$albumId'
    | '/_app/artists/$artistId/albums/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupPasswordRoute: typeof SetupPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/password': {
      id: '/setup/password'
      path: '/setup/password'
      fullPath: '/setup/password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wanted': {
      id: '/_app/wanted'
      path: '/wanted'
      fullPath: '/wanted'
      preLoaderRoute: typeof AppWantedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads': {
      id: '/_app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artists': {
      id: '/_app/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof AppArtistsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/library/': {
      id: '/_app/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppLibraryRouteRoute
    }
    '/_app/import/': {
      id: '/_app/import/'
      path: '/'
      fullPath: '/import/'
      preLoaderRoute: typeof AppImportIndexRouteImport
      parentRoute: typeof AppImportRouteRoute
    }
    '/_app/artists/': {
      id: '/_app/artists/'
      path: '/'
      fullPath: '/artists/'
      preLoaderRoute: typeof AppArtistsIndexRouteImport
      parentRoute: typeof AppArtistsRouteRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/library/tracks': {
      id: '/_app/library/tracks'
      path: '/tracks'
      fullPath: '/library/tracks'
      preLoaderRoute: typeof AppLibraryTracksRouteImport
      parentRoute: typeof AppLibraryRouteRoute
    }
    '/_app/library/artists': {
      id: '/_app/library/artists'
      path: '/artists'
      fullPath: '/library/artists'
      preLoaderRoute: typeof AppLibraryArtistsRouteImport
      parentRoute: typeof AppLibraryRouteRoute
    }
    '/_app/library/albums': {
      id: '/_app/library/albums'
      path: '/albums'
      fullPath: '/library/albums'
      preLoaderRoute: typeof AppLibraryAlbumsRouteImport
      parentRoute: typeof AppLibraryRouteRoute
    }
    '/_app/artists/$artistId': {
      id: '/_app/artists/$artistId'
      path: '/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof AppArtistsArtistIdRouteImport
      parentRoute: typeof AppArtistsRouteRoute
    }
    '/_app/artists/$artistId/': {
      id: '/_app/artists/$artistId/'
      path: '/'
      fullPath: '/artists/$artistId/'
      preLoaderRoute: typeof AppArtistsArtistIdIndexRouteImport
      parentRoute: typeof AppArtistsArtistIdRoute
    }
    '/_app/artists/$artistId/merge-albums': {
      id: '/_app/artists/$artistId/merge-albums'
      path: '/merge-albums'
      fullPath: '/artists/$artistId/merge-albums'
      preLoaderRoute: typeof AppArtistsArtistIdMergeAlbumsRouteImport
      parentRoute: typeof AppArtistsArtistIdRoute
    }
    '/_app/artists/$artistId/albums': {
      id: '/_app/artists/$artistId/albums'
      path: '/albums'
      fullPath: '/artists/$artistId/albums'
      preLoaderRoute: typeof AppArtistsArtistIdAlbumsRouteImport
      parentRoute: typeof AppArtistsArtistIdRoute
    }
    '/_app/artists/$artistId/albums/': {
      id: '/_app/artists/$artistId/albums/'
      path: '/'
      fullPath: '/artists/$artistId/albums/'
      preLoaderRoute: typeof AppArtistsArtistIdAlbumsIndexRouteImport
      parentRoute: typeof AppArtistsArtistIdAlbumsRoute
    }
    '/_app/artists/$artistId/albums/$albumId': {
      id: '/_app/artists/$artistId/albums/$albumId'
      path: '/$albumId'
      fullPath: '/artists/$artistId/albums/$albumId'
      preLoaderRoute: typeof AppArtistsArtistIdAlbumsAlbumIdRouteImport
      parentRoute: typeof AppArtistsArtistIdAlbumsRoute
    }
  }
}

interface AppArtistsArtistIdAlbumsRouteChildren {
  AppArtistsArtistIdAlbumsAlbumIdRoute: typeof AppArtistsArtistIdAlbumsAlbumIdRoute
  AppArtistsArtistIdAlbumsIndexRoute: typeof AppArtistsArtistIdAlbumsIndexRoute
}

const AppArtistsArtistIdAlbumsRouteChildren: AppArtistsArtistIdAlbumsRouteChildren =
  {
    AppArtistsArtistIdAlbumsAlbumIdRoute: AppArtistsArtistIdAlbumsAlbumIdRoute,
    AppArtistsArtistIdAlbumsIndexRoute: AppArtistsArtistIdAlbumsIndexRoute,
  }

const AppArtistsArtistIdAlbumsRouteWithChildren =
  AppArtistsArtistIdAlbumsRoute._addFileChildren(
    AppArtistsArtistIdAlbumsRouteChildren,
  )

interface AppArtistsArtistIdRouteChildren {
  AppArtistsArtistIdAlbumsRoute: typeof AppArtistsArtistIdAlbumsRouteWithChildren
  AppArtistsArtistIdMergeAlbumsRoute: typeof AppArtistsArtistIdMergeAlbumsRoute
  AppArtistsArtistIdIndexRoute: typeof AppArtistsArtistIdIndexRoute
}

const AppArtistsArtistIdRouteChildren: AppArtistsArtistIdRouteChildren = {
  AppArtistsArtistIdAlbumsRoute: AppArtistsArtistIdAlbumsRouteWithChildren,
  AppArtistsArtistIdMergeAlbumsRoute: AppArtistsArtistIdMergeAlbumsRoute,
  AppArtistsArtistIdIndexRoute: AppArtistsArtistIdIndexRoute,
}

const AppArtistsArtistIdRouteWithChildren =
  AppArtistsArtistIdRoute._addFileChildren(AppArtistsArtistIdRouteChildren)

interface AppArtistsRouteRouteChildren {
  AppArtistsArtistIdRoute: typeof AppArtistsArtistIdRouteWithChildren
  AppArtistsIndexRoute: typeof AppArtistsIndexRoute
}

const AppArtistsRouteRouteChildren: AppArtistsRouteRouteChildren = {
  AppArtistsArtistIdRoute: AppArtistsArtistIdRouteWithChildren,
  AppArtistsIndexRoute: AppArtistsIndexRoute,
}

const AppArtistsRouteRouteWithChildren = AppArtistsRouteRoute._addFileChildren(
  AppArtistsRouteRouteChildren,
)

interface AppImportRouteRouteChildren {
  AppImportIndexRoute: typeof AppImportIndexRoute
}

const AppImportRouteRouteChildren: AppImportRouteRouteChildren = {
  AppImportIndexRoute: AppImportIndexRoute,
}

const AppImportRouteRouteWithChildren = AppImportRouteRoute._addFileChildren(
  AppImportRouteRouteChildren,
)

interface AppLibraryRouteRouteChildren {
  AppLibraryAlbumsRoute: typeof AppLibraryAlbumsRoute
  AppLibraryArtistsRoute: typeof AppLibraryArtistsRoute
  AppLibraryTracksRoute: typeof AppLibraryTracksRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
}

const AppLibraryRouteRouteChildren: AppLibraryRouteRouteChildren = {
  AppLibraryAlbumsRoute: AppLibraryAlbumsRoute,
  AppLibraryArtistsRoute: AppLibraryArtistsRoute,
  AppLibraryTracksRoute: AppLibraryTracksRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
}

const AppLibraryRouteRouteWithChildren = AppLibraryRouteRoute._addFileChildren(
  AppLibraryRouteRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppArtistsRouteRoute: typeof AppArtistsRouteRouteWithChildren
  AppImportRouteRoute: typeof AppImportRouteRouteWithChildren
  AppLibraryRouteRoute: typeof AppLibraryRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDownloadsRoute: typeof AppDownloadsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWantedRoute: typeof AppWantedRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArtistsRouteRoute: AppArtistsRouteRouteWithChildren,
  AppImportRouteRoute: AppImportRouteRouteWithChildren,
  AppLibraryRouteRoute: AppLibraryRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDownloadsRoute: AppDownloadsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWantedRoute: AppWantedRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupPasswordRoute: SetupPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
